export const routes = {
  home: "/",
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    verify: "/auth/verify",
  },
  workspace: {
    index: "/w",
    bySlug: (slug: string) => `/w/${slug}`,
    settings: (slug: string) => `/w/${slug}/settings`,
    members: (slug: string) => `/w/${slug}/members`,
    events: (slug: string) => `/w/${slug}/events`,
    projects: (slug: string) => `/w/${slug}/projects`,
    ideas: (slug: string) => `/w/${slug}/ideas`,
    tasks: (slug: string) => `/w/${slug}/tasks`,
    research: (slug: string) => `/w/${slug}/research`,
    files: (slug: string) => `/w/${slug}/files`,
    submissions: (slug: string) => `/w/${slug}/submissions`,
    judging: (slug: string) => `/w/${slug}/judging`,
    archive: (slug: string) => `/w/${slug}/archive`,
    team: (slug: string) => `/w/${slug}/team`,
    activity: (slug: string) => `/w/${slug}/activity`,
  },
  settings: {
    profile: "/settings/profile",
    account: "/settings/account",
    appearance: "/settings/appearance",
    notifications: "/settings/notifications",
  },
  notFound: "/404",
  forbidden: "/403",
  error: "/500",
  maintenance: "/maintenance",
} as const;
